tasks:
  - name: Script Task
    init: yarn
    command: yarn run dev

ports:
  - name: Frontend
    description: Port 5173 for the frontend
    port: 5173
    onOpen: open-preview
    protocol: https
